---
title: Nazariya - Grassroot
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Squareyes
email: info@squareyes.info
description: '
'
permalink: pretty
exclude:
- Gemfile.lock
- Gemfile
- README*
- node_modules
- ".gitignore"
- assets/scripts/src
- yarn.lock
- ".git"
sass:
  sass_dir: assets/styles/
  style: compressed
plugins:
- jekyll-autoprefixer
