---
title: Focus Fair
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
meta: FOCUS is an annual camera and zine fair. Bringing together some of the best
  camera hoarders and printed matter enthusiasts Australia has to offer.
