---
title: Focus Fair
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Squareyes
email: info@squareyes.info
description: 'FOCUS is an annual camera and zine fair. Bringing together some of the
  best camera hoarders and printed matter enthusiasts Australia has to offer.

'
permalink: pretty
exclude:
- Gemfile.lock
- Gemfile
- README*
- node_modules
- ".gitignore"
- assets/scripts/src
- yarn.lock
- ".git"
sass:
  sass_dir: assets/styles/
  style: compressed
plugins:
- jekyll-autoprefixer